# fly.toml app configuration file generated for pdm-app-two-ancient-snow-6330 on 2024-01-23T16:05:18-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pdm-app-two-ancient-snow-6330"
primary_region = "ewr"

[build]

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
